# Generated by Django 4.2.16 on 2024-11-12 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_wrappedsummary'),
    ]

    operations = [
        migrations.AddField(
            model_name='wrappedsummary',
            name='playlists',
            field=models.JSONField(default=[]),
            preserve_default=False,
        ),
    ]
