# Generated by Django 4.2.16 on 2024-11-12 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_spotifydata"),
    ]

    operations = [
        migrations.AlterField(
            model_name="spotifydata",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
