# Generated by Django 4.2.16 on 2024-11-25 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_spotifydata_insights"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="spotify_access_token",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="spotify_refresh_token",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="spotify_token_expires",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
